name: Deploy to Cloudflare Workers

on:
  push:
  pull_request:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - run: rm -rf pnpm-lock.yaml
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          secrets: |
            RECAPTCHA_SECRET_KEY
            TURNSTILE_SECRET_KEY
        env:
          RECAPTCHA_SECRET_KEY: ${{ secrets.CLOUDFLARE_RECAPTCHA_SECRET_KEY }}
          TURNSTILE_SECRET_KEY: ${{ secrets.CLOUDFLARE_TURNSTILE_SECRET_KEY }}
